### ISSUE TITLE
Program crashes :( help pls

### ISSUE THREAD

**Issue by AmenitradieDruidin** [Marlamin/WoWExportTools#44]
Hello, use the Blender **version 2.80.**
As soon as I want to load a map, the program crashes. Or I get error messages. (see image)
![Unbengannt-1](https://user-images.githubusercontent.com/39033070/63357562-eefc3800-c369-11e9-8d61-d2ef5a2e2248.jpg)

**Comment by TheRebelSpy** [comment]
I have a similar issue and am also using Blender 2.80.

I receive the same traceback error after using the ADT addon to import expansion01_55_39.obj.

(By the way thank you Marlamin for creating this. I have been having so much fun.)

![adterror](https://user-images.githubusercontent.com/54345402/63403593-c63d6800-c394-11e9-93be-e1b32b0562e6.jpg)

**Comment by Marlamin** [comment]
So for some reason it added a .001 in the screenshot you posted which makes the plugin unable to find it right after importing. Will hopefully have time this weekend to check.

**Comment by Marlamin** [comment]
Was able to reproduce the issue, this happens when you import the same object twice in a single Blender session/save. Importing something of the same name twice appends a .001. Then when the original model (without the .001) is deleted, the plugin can't parent submodels to anything. My Blender/Python knowledge is a bit too limited to think of a proper fix so I can only suggest to not import the same thing twice.

As for @TheRebelSpy's issue, I wasn't able to replicate this. If you're still experiencing this please open up a separate GitHub issue so I can investigate.

**Comment by AmenitradieDruidin** [comment]
Hi first of all thank you have looked where the problem lies.
Unfortunately, I always get an error when I want to insert an object via ADT OBJ.
Even if I want to insert objects from the old world eg. Kalimdor.
And I did not import them twice.
Both error messages on the picture have been imported into a new session.

![jj](https://user-images.githubusercontent.com/39033070/63636518-a649c500-c670-11e9-8eca-974fee1bd902.jpg)

**Comment by Marlamin** [comment]
That was issue #43 which has been fixed in the new version, please check if that resolves it. Don't forget to update the Blender plugin.
